### ISSUE TITLE
Add the TailwindUI colors

### ISSUE THREAD

**Issue by jpwain** [impulse/tailwindcss-figma-kit#9]
The [changelog indicates](https://github.com/impulse/tailwindcss-figma-kit/commit/7e2d91639597686f8d63277cc293c92536718e3c) that TailwindUI colors are added, but when inspecting the latest .fig file, the colors available don't match [the Tailwind UI documentation](https://tailwindui.com/documentation#how-tailwindcss-ui-extends-tailwind), and don't include the `50` shade of each color. Not sure what the mismatch is — is the wrong file published?

**Comment by impulse** [comment]
@jpwain actually I accidentally added the colors based on a default tailwind config 😆. Should be fixed now, thanks for pointing it out!

**Comment by jpwain** [comment]
@impulse Heads up that the .fig file still doesn't have the Tailwind colors or the `50` shades...

**Comment by impulse** [comment]
> @impulse Heads up that the .fig file still doesn't have the Tailwind colors or the `50` shades...

Are you sure? I just downloaded the file and it has all shades (make sure to scroll down for the tailwindui prefixed colors)

**Comment by jpwain** [comment]
I see now: the styles are present, but I was looking at the swatches. Sorted, thanks :)
